repo_name: projectcapsule/capsule
repo_url: https://github.com/projectcapsule/capsule

site_name: Capsule
site_url: https://capsule.clastix.io/
docs_dir: content
site_dir: site
site_author: bsctl
site_description: >-
  Multi-tenancy and policy-based framework for Kubernetes
copyright: >-
  Copyright &copy; 2020-2023 Capsule Authors | Copyright &copy; 2023 The Linux Foundation.

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.footer
    - content.code.copy
  include_sidebar: true
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      #scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  #favicon: assets/logo/favicon.png
  logo: assets/logo/capsule.png

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html

# Generate navigation bar
nav:
- 'Overview': concepts.md
- 'Getting started': getting-started.md
- 'Tutorial': tutorial.md
- 'Capsule Proxy':
  - proxy/index.md
  - proxy/overview.md
  - proxy/install.md
  - proxy/resources.md
  - proxy/metrics.md
  - proxy/reference.md
- 'Guides':
  - guides/index.md
  - guides/oidc-auth.md
  - guides/monitoring.md
  - guides/kubernetes-dashboard.md
  - guides/velero.md
  - guides/upgrade.md
  - guides/flux.md
  - guides/charmed.md
  - guides/pod-security.md
  - guides/coaks.md
  - guides/eks.md
- 'Rancher':
  - rancher/index.md
  - rancher/capsule-rancher.md
  - rancher/capsule-proxy-rancher.md
  - rancher/oidc.md
- 'Reference':
  - reference/index.md
  - reference/crds-apis.md
  - reference/mtb.md
- 'Contribute':
  - 'contribute/guidelines.md'
  - 'contribute/development.md'
  - 'contribute/governance.md'
  - 'contribute/release.md'